services:
  - type: web
    name: chickpea-disease-model
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    region: singapore            # or ohio/frankfurt
    plan: free
    autoDeploy: true
